---
mosquitto:
    ip: "192.168.178.34"
    port: 1883

log:
    dir: "/Users/schwenger/Workspace/rusty_home/log"
    format: "%(levelname)s\t%(asctime)s\t%(name)s::%(filename)s:%(lineno)d → %(message)s"

home:
    dir: "/Users/schwenger/Workspace/rusty_home/config/home.yml"